// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMzW0nEQndUCpaDH-0UjKal867lmYlUJ4',
    appId: '1:388732329252:web:97b0dbded658853ce667b1',
    messagingSenderId: '388732329252',
    projectId: 'trailerbaaz-71fa4',
    authDomain: 'trailerbaaz-71fa4.firebaseapp.com',
    storageBucket: 'trailerbaaz-71fa4.firebasestorage.app',
    measurementId: 'G-1DTHV08T3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86phYzMGzwv4BzHCcJ3OOof2uqwp4v3M',
    appId: '1:388732329252:android:8d8653d9d12a6a8ae667b1',
    messagingSenderId: '388732329252',
    projectId: 'trailerbaaz-71fa4',
    storageBucket: 'trailerbaaz-71fa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASPEEKjeCg7U4xTlbhjNCjf25UjSnmRMc',
    appId: '1:388732329252:ios:ada77b748483f930e667b1',
    messagingSenderId: '388732329252',
    projectId: 'trailerbaaz-71fa4',
    storageBucket: 'trailerbaaz-71fa4.firebasestorage.app',
    androidClientId: '388732329252-cen8o1qc64a8ijf07m3coial5itslpe6.apps.googleusercontent.com',
    iosClientId: '388732329252-okuk3iblnqddi6en5k36ne9u2ujq01rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.trailerBaazMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASPEEKjeCg7U4xTlbhjNCjf25UjSnmRMc',
    appId: '1:388732329252:ios:ada77b748483f930e667b1',
    messagingSenderId: '388732329252',
    projectId: 'trailerbaaz-71fa4',
    storageBucket: 'trailerbaaz-71fa4.firebasestorage.app',
    androidClientId: '388732329252-cen8o1qc64a8ijf07m3coial5itslpe6.apps.googleusercontent.com',
    iosClientId: '388732329252-okuk3iblnqddi6en5k36ne9u2ujq01rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.trailerBaazMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMzW0nEQndUCpaDH-0UjKal867lmYlUJ4',
    appId: '1:388732329252:web:e860f8aa8b0a2b9ce667b1',
    messagingSenderId: '388732329252',
    projectId: 'trailerbaaz-71fa4',
    authDomain: 'trailerbaaz-71fa4.firebaseapp.com',
    storageBucket: 'trailerbaaz-71fa4.firebasestorage.app',
    measurementId: 'G-NTYPE4XX7Q',
  );
}
