import '../models/vehicle.dart';
import '../models/membership.dart';
import '../models/faq.dart';

class FleetRepository {
  static final List<Vehicle> fleetData = [
    const Vehicle(
      id: 1,
      slug: 'ferrari-sf90',
      name: 'Ferrari SF90 Stradale',
      tagline: '1000 Horsepower Hybrid Masterpiece',
      category: 'coupe',
      pricePerDay: 2000,
      pricePerWeek: 12000,
      specs: VehicleSpecs(
        engine: '4.0L Twin-Turbo V8 Hybrid',
        power: '1000 hp',
        torque: '800 Nm',
        zeroToSixty: '2.5s',
        topSpeed: '340 km/h',
        seats: 2,
        transmission: 'auto',
        fuel: 'hybrid',
        year: 2024,
        doors: 2,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15059594baa062d4b976.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15059594baa062d4b976.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15059594baa062d4b976.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Rosso Corsa', hex: '#C0392B'),
        VehicleColor(name: 'Nero Noctis', hex: '#1A1A1A'),
      ],
      features: ['2 Seats', 'Auto', 'Hybrid', '2.5s 0-60', 'E-Drive Mode'],
      featured: true,
      available: true,
      badge: "Editor's Pick",
    ),
    const Vehicle(
      id: 2,
      slug: 'lamborghini-revuelto',
      name: 'Lamborghini Revuelto',
      tagline: 'V12 Hybrid HPEV Supercar',
      category: 'coupe',
      pricePerDay: 2200,
      pricePerWeek: 13500,
      specs: VehicleSpecs(
        engine: '6.5L V12 Hybrid',
        power: '1015 hp',
        torque: '807 Nm',
        zeroToSixty: '2.5s',
        topSpeed: '350 km/h',
        seats: 2,
        transmission: 'auto',
        fuel: 'hybrid',
        year: 2024,
        doors: 2,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15050394c98503503cc7.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15050394c98503503cc7.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15050394c98503503cc7.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Arancio Apodis', hex: '#D45B12'),
        VehicleColor(name: 'Verde Turbine', hex: '#2A4D38'),
      ],
      features: ['2 Seats', 'Auto', 'V12 Hybrid', '2.5s 0-60', 'Monofuselage Chassis'],
      featured: true,
      available: true,
      badge: 'New Arrival',
    ),
    const Vehicle(
      id: 3,
      slug: 'porsche-911-gt3rs',
      name: 'Porsche 911 GT3 RS',
      tagline: 'Track-focused aerodynamic performance',
      category: 'coupe',
      pricePerDay: 1600,
      pricePerWeek: 10000,
      specs: VehicleSpecs(
        engine: '4.0L Naturally Aspirated Flat-6',
        power: '525 hp',
        torque: '465 Nm',
        zeroToSixty: '3.2s',
        topSpeed: '296 km/h',
        seats: 2,
        transmission: 'auto',
        fuel: 'petrol',
        year: 2024,
        doors: 2,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1504516b813067bad92f.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1504516b813067bad92f.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1504516b813067bad92f.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Guards Red', hex: '#A93226'),
        VehicleColor(name: 'GT Silver Metallic', hex: '#BDC3C7'),
      ],
      features: ['2 Seats', 'Auto', 'Flat-6 Petrol', '3.2s 0-60', 'DRS System'],
      featured: true,
      available: true,
      badge: 'Most Popular',
    ),
    const Vehicle(
      id: 4,
      slug: 'aston-martin-dbs',
      name: 'Aston Martin DBS Superleggera',
      tagline: 'The Ultimate Grand Tourer',
      category: 'coupe',
      pricePerDay: 1500,
      pricePerWeek: 9500,
      specs: VehicleSpecs(
        engine: '5.2L Twin-Turbo V12',
        power: '715 hp',
        torque: '900 Nm',
        zeroToSixty: '3.4s',
        topSpeed: '340 km/h',
        seats: 4,
        transmission: 'auto',
        fuel: 'petrol',
        year: 2023,
        doors: 2,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15047167fd9a35bd0435.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15047167fd9a35bd0435.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15047167fd9a35bd0435.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Xenon Grey', hex: '#4A5568'),
        VehicleColor(name: 'British Racing Green', hex: '#1E4620'),
      ],
      features: ['4 Seats', 'Auto', 'V12 Petrol', '3.4s 0-60', 'Bang & Olufsen Audio'],
      featured: true,
      available: true,
    ),
    const Vehicle(
      id: 5,
      slug: 'rolls-royce-spectre',
      name: 'Rolls-Royce Spectre',
      tagline: 'Whisper-Quiet Electric Luxury',
      category: 'ev',
      pricePerDay: 2500,
      pricePerWeek: 15000,
      specs: VehicleSpecs(
        engine: 'Dual-Motor Electric',
        power: '584 hp',
        torque: '900 Nm',
        range: '530 km',
        zeroToSixty: '4.4s',
        topSpeed: '250 km/h',
        seats: 4,
        transmission: 'auto',
        fuel: 'electric',
        year: 2024,
        doors: 2,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15047167fd9a35bd0434.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15047167fd9a35bd0434.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15047167fd9a35bd0434.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Chartreuse Gloss', hex: '#A2B997'),
        VehicleColor(name: 'English White', hex: '#F0ECE1'),
      ],
      features: ['4 Seats', 'Auto', 'Electric', '530 km range', 'Starlight Doors'],
      featured: true,
      available: true,
      badge: 'Limited Privilege',
    ),
    const Vehicle(
      id: 6,
      slug: 'mercedes-g63',
      name: 'Mercedes-AMG G 63',
      tagline: 'Iconic Design. Brutal V8 Power.',
      category: 'suv',
      pricePerDay: 1400,
      pricePerWeek: 8800,
      specs: VehicleSpecs(
        engine: '4.0L Bi-Turbo V8',
        power: '577 hp',
        torque: '850 Nm',
        zeroToSixty: '4.5s',
        topSpeed: '220 km/h',
        seats: 5,
        transmission: 'auto',
        fuel: 'petrol',
        year: 2024,
        doors: 5,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1505516b813067bad94d.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1505516b813067bad94d.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1505516b813067bad94d.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Monza Grey', hex: '#63666A'),
        VehicleColor(name: 'Obsidian Black', hex: '#111111'),
      ],
      features: ['5 Seats', 'Auto', 'V8 Petrol', 'AWD Differential Locks', 'Active Ride Control'],
      featured: false,
      available: true,
    ),
    const Vehicle(
      id: 7,
      slug: 'range-rover-sv',
      name: 'Range Rover SV Autobiography',
      tagline: 'First-Class Luxury for Any Path',
      category: 'suv',
      pricePerDay: 1200,
      pricePerWeek: 7500,
      specs: VehicleSpecs(
        engine: '4.4L Twin-Turbo V8 Hybrid',
        power: '523 hp',
        torque: '750 Nm',
        zeroToSixty: '4.6s',
        topSpeed: '250 km/h',
        seats: 5,
        transmission: 'auto',
        fuel: 'hybrid',
        year: 2024,
        doors: 5,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1505516b813067bad94c.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1505516b813067bad94c.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1505516b813067bad94c.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Sunset Gold', hex: '#CDBA96'),
        VehicleColor(name: 'Santorini Black', hex: '#0F0F14'),
      ],
      features: ['5 Seats', 'Auto', 'Hybrid', 'Executive Seating', 'Fridge Console'],
      featured: false,
      available: true,
    ),
    const Vehicle(
      id: 8,
      slug: 'audi-rs-etron',
      name: 'Audi RS e-tron GT',
      tagline: 'Electric Performance Refined',
      category: 'ev',
      pricePerDay: 1100,
      pricePerWeek: 7000,
      specs: VehicleSpecs(
        engine: 'Dual Electric Motors',
        power: '637 hp',
        torque: '830 Nm',
        range: '472 km',
        zeroToSixty: '3.3s',
        topSpeed: '250 km/h',
        seats: 5,
        transmission: 'auto',
        fuel: 'electric',
        year: 2024,
        doors: 4,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fd85d0bc1f77cc35e5ba04.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fd85d0bc1f77cc35e5ba04.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fd85d0bc1f77cc35e5ba04.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Kemora Gray', hex: '#707B7C'),
        VehicleColor(name: 'Mythos Black', hex: '#1B1C1C'),
      ],
      features: ['5 Seats', 'Auto', 'Electric', '3.3s 0-60', 'quattro AWD'],
      featured: false,
      available: true,
    ),
    const Vehicle(
      id: 9,
      slug: 'bmw-m8',
      name: 'BMW M8 Competition Gran Coupe',
      tagline: 'Track Heritage Meets Luxury Space',
      category: 'sedan',
      pricePerDay: 1000,
      pricePerWeek: 6300,
      specs: VehicleSpecs(
        engine: '4.4L TwinPower V8',
        power: '617 hp',
        torque: '750 Nm',
        zeroToSixty: '3.0s',
        topSpeed: '305 km/h',
        seats: 5,
        transmission: 'auto',
        fuel: 'petrol',
        year: 2024,
        doors: 4,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1504516b813067bad937.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1504516b813067bad937.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1504516b813067bad937.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Brands Hatch Grey', hex: '#7B7D7D'),
        VehicleColor(name: 'Alpine White', hex: '#FFFFFF'),
      ],
      features: ['5 Seats', 'Auto', 'V8 Petrol', '3.0s 0-60', 'M xDrive AWD'],
      featured: false,
      available: true,
    ),
    const Vehicle(
      id: 10,
      slug: 'bentley-continental',
      name: 'Bentley Continental GT',
      tagline: 'Modern Grand Tourer of Exquisite Design',
      category: 'coupe',
      pricePerDay: 1700,
      pricePerWeek: 10500,
      specs: VehicleSpecs(
        engine: '6.0L Twin-Turbo W12',
        power: '626 hp',
        torque: '900 Nm',
        zeroToSixty: '3.6s',
        topSpeed: '333 km/h',
        seats: 4,
        transmission: 'auto',
        fuel: 'petrol',
        year: 2024,
        doors: 2,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15059594baa062d4b974.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15059594baa062d4b974.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15059594baa062d4b974.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Dark Sapphire', hex: '#1C2833'),
        VehicleColor(name: 'Glacier White', hex: '#FBFCFC'),
      ],
      features: ['4 Seats', 'Auto', 'W12 Petrol', '3.6s 0-60', 'Mulliner Spec'],
      featured: false,
      available: true,
    ),
    const Vehicle(
      id: 11,
      slug: 'maserati-mc20',
      name: 'Maserati MC20 Cielo',
      tagline: 'Art in Motion. Italian Roadster Soul.',
      category: 'roadster',
      pricePerDay: 1800,
      pricePerWeek: 11000,
      specs: VehicleSpecs(
        engine: '3.0L twin-turbo V6 Nettuno',
        power: '621 hp',
        torque: '730 Nm',
        zeroToSixty: '2.9s',
        topSpeed: '325 km/h',
        seats: 2,
        transmission: 'auto',
        fuel: 'petrol',
        year: 2024,
        doors: 2,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1504516b813067bad939.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1504516b813067bad939.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb1504516b813067bad939.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Acquamarina Blue', hex: '#85C1E9'),
        VehicleColor(name: 'Bianco Audace', hex: '#EAEDED'),
      ],
      features: ['2 Seats', 'Auto', 'Petrol V6', '2.9s 0-60', 'Glass Electrochromic Roof'],
      featured: false,
      available: true,
    ),
    const Vehicle(
      id: 12,
      slug: 'ferrari-f8-spider',
      name: 'Ferrari F8 Spider',
      tagline: 'V8 Open-Air Symphonic Performance',
      category: 'roadster',
      pricePerDay: 1900,
      pricePerWeek: 11800,
      specs: VehicleSpecs(
        engine: '3.9L Twin-Turbo V8',
        power: '710 hp',
        torque: '770 Nm',
        zeroToSixty: '2.9s',
        topSpeed: '340 km/h',
        seats: 2,
        transmission: 'auto',
        fuel: 'petrol',
        year: 2023,
        doors: 2,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15040394c98503503cb4.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15040394c98503503cb4.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15040394c98503503cb4.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Giallo Modena', hex: '#F4D03F'),
        VehicleColor(name: 'Rosso Scuderia', hex: '#EC7063'),
      ],
      features: ['2 Seats', 'Auto', 'Petrol V8', '2.9s 0-60', 'Retractable Hard Top'],
      featured: false,
      available: true,
    ),
    const Vehicle(
      id: 13,
      slug: 'porsche-taycan',
      name: 'Porsche Taycan Turbo S',
      tagline: 'Electric Sportscar Luxury',
      category: 'ev',
      pricePerDay: 1150,
      pricePerWeek: 7200,
      specs: VehicleSpecs(
        engine: 'Dual Electric Motors',
        power: '750 hp',
        torque: '1050 Nm',
        range: '412 km',
        zeroToSixty: '2.6s',
        topSpeed: '260 km/h',
        seats: 4,
        transmission: 'auto',
        fuel: 'electric',
        year: 2024,
        doors: 4,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15057167fd9a35bd0446.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15057167fd9a35bd0446.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15057167fd9a35bd0446.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Frozen Blue Metallic', hex: '#A9CCE3'),
        VehicleColor(name: 'Jet Black Metallic', hex: '#1C2833'),
      ],
      features: ['4 Seats', 'Auto', 'Electric', '2.6s 0-60', '800V Architecture'],
      featured: false,
      available: true,
    ),
    const Vehicle(
      id: 14,
      slug: 'mclaren-720s',
      name: 'McLaren 720S Spider',
      tagline: 'Lightweight Carbon-Monocoque Thrill',
      category: 'coupe',
      pricePerDay: 1850,
      pricePerWeek: 11500,
      specs: VehicleSpecs(
        engine: '4.0L Twin-Turbo V8',
        power: '710 hp',
        torque: '770 Nm',
        zeroToSixty: '2.8s',
        topSpeed: '341 km/h',
        seats: 2,
        transmission: 'auto',
        fuel: 'petrol',
        year: 2023,
        doors: 2,
      ),
      images: VehicleImages(
        thumbnail: 'https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15050394c98503503cc6.jpg',
        exterior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15050394c98503503cc6.jpg'],
        interior: ['https://assets.cdn.filesafe.space/K8MDlk08iBMTjnnknE3G/media/69fb15050394c98503503cc6.jpg'],
      ),
      colors: [
        VehicleColor(name: 'Aurora Blue', hex: '#2471A3'),
        VehicleColor(name: 'Volcano Orange', hex: '#E67E22'),
      ],
      features: ['2 Seats', 'Auto', 'V8 Petrol', '2.8s 0-60', 'Dihedral Doors'],
      featured: false,
      available: true,
    ),
  ];

  static final List<FAQItem> faqData = [
    const FAQItem(
      id: 1,
      category: 'booking',
      question: 'How quickly can I confirm a booking?',
      answer: 'Scout members receive confirmation within 2 hours. Vantage members get same-day confirmation within 4 hours. Apex members receive instant confirmation — bookings are approved automatically the moment you submit.',
    ),
    const FAQItem(
      id: 2,
      category: 'booking',
      question: 'What documents do I need to rent a vehicle?',
      answer: 'You\'ll need a valid UAE driving licence (or an international licence with a notarised Arabic translation), a passport copy, and a credit card for the security deposit. GCC nationals may use their national ID. All verification is done digitally through the SAFRA app.',
    ),
    const FAQItem(
      id: 3,
      category: 'booking',
      question: 'Can I modify or cancel my booking?',
      answer: 'Yes. Modifications are free up to 48 hours before pick-up. Cancellations made more than 48 hours before are fully refunded. Late cancellations (within 48 hours) incur a 1-day rental fee. Apex members enjoy flexible cancellation at any time without penalty.',
    ),
    const FAQItem(
      id: 4,
      category: 'booking',
      question: 'Is there a minimum rental period?',
      answer: 'Our minimum rental is 24 hours. We also offer weekly and monthly rates with significant discounts — 15% off for 7+ days, 25% off for 30+ days, plus any membership discount stacked on top.',
    ),
    const FAQItem(
      id: 5,
      category: 'insurance',
      question: 'What insurance coverage is included?',
      answer: 'Every SAFRA rental includes comprehensive insurance covering third-party liability, collision damage waiver (CDW), and theft protection. Our standard excess is AED 3,000. Apex members enjoy zero-excess coverage at no additional cost.',
    ),
    const FAQItem(
      id: 6,
      category: 'insurance',
      question: 'Can I reduce or eliminate the excess?',
      answer: 'Yes. You can add Super Coverage at checkout (AED 120–280/day depending on vehicle class), reducing your excess to zero. Alternatively, Apex membership includes zero-excess as a standard perk.',
    ),
    const FAQItem(
      id: 7,
      category: 'insurance',
      question: 'What happens if there is an accident?',
      answer: 'Contact our 24/7 concierge line immediately. We\'ll coordinate police reports, towing, and a replacement vehicle for Vantage and Apex members. Our team handles all insurance paperwork — you focus on getting safely to your destination.',
    ),
    const FAQItem(
      id: 8,
      category: 'delivery',
      question: 'Do you offer vehicle delivery and collection?',
      answer: 'Yes. We deliver to any address in the UAE — hotels, residences, offices, and all major airports. Vantage members receive free delivery within Dubai. Apex members receive free delivery anywhere in the UAE, at any hour.',
    ),
    const FAQItem(
      id: 9,
      category: 'delivery',
      question: 'How far in advance should I book for airport delivery?',
      answer: 'We recommend booking at least 6 hours ahead for airport deliveries to guarantee your preferred vehicle. During peak periods (UAE National Day, Dubai Shopping Festival) we suggest 24–48 hours advance booking. Apex members are always prioritised.',
    ),
    const FAQItem(
      id: 10,
      category: 'pricing',
      question: 'What payment methods do you accept?',
      answer: 'We accept all major credit cards (Visa, Mastercard, Amex), Apple Pay, Google Pay, and UAE bank transfers for corporate accounts. A security deposit (equal to 2 days\' rental) is pre-authorised on your card and released within 5 business days of return.',
    ),
    const FAQItem(
      id: 11,
      category: 'pricing',
      question: 'Are there any hidden fees?',
      answer: 'No. Your booking total includes insurance, basic roadside support, and all standard taxes. Extras — like additional drivers, child seats, GPS, or fuel pre-purchase — are listed clearly at checkout. What you see is what you pay.',
    ),
    const FAQItem(
      id: 12,
      category: 'membership',
      question: 'Can I upgrade or downgrade my membership?',
      answer: 'Yes, at any time. Upgrades take effect immediately. Downgrades take effect at the start of your next billing cycle. If you upgrade mid-cycle, you\'ll only pay the prorated difference for the remaining days.',
    ),
  ];

  static final List<MembershipTier> membershipTiers = [
    const MembershipTier(
      id: 1,
      name: 'Scout',
      tagline: 'The perfect starting point',
      pricePerMonth: 0,
      features: [
        MembershipFeature(text: 'Access to full fleet catalogue', included: true),
        MembershipFeature(text: 'Standard booking confirmation', included: true),
        MembershipFeature(text: '10% discount on weekly rentals', included: true),
        MembershipFeature(text: 'Basic roadside support', included: true),
        MembershipFeature(text: 'Priority fleet selection', included: false),
        MembershipFeature(text: 'Airport concierge delivery', included: false),
        MembershipFeature(text: 'Exclusive member events', included: false),
        MembershipFeature(text: 'Personal account manager', included: false),
      ],
      highlighted: false,
      ctaLabel: 'Start for Free',
    ),
    const MembershipTier(
      id: 2,
      name: 'Vantage',
      tagline: 'The curated driving life',
      pricePerMonth: 299,
      pricePerYear: 2990,
      features: [
        MembershipFeature(text: 'Access to full fleet catalogue', included: true),
        MembershipFeature(text: 'Same-day booking confirmation', included: true),
        MembershipFeature(text: '20% discount on all rentals', included: true),
        MembershipFeature(text: '24/7 premium roadside support', included: true),
        MembershipFeature(text: 'Priority fleet selection', included: true),
        MembershipFeature(text: 'Airport concierge delivery', included: true),
        MembershipFeature(text: 'Exclusive member events', included: false),
        MembershipFeature(text: 'Personal account manager', included: false),
      ],
      highlighted: true,
      badge: 'Most Popular',
      ctaLabel: 'Join Vantage',
    ),
    const MembershipTier(
      id: 3,
      name: 'Apex',
      tagline: 'No limits. No waiting.',
      pricePerMonth: 799,
      pricePerYear: 7990,
      features: [
        MembershipFeature(text: 'Unlimited fleet access — any model', included: true),
        MembershipFeature(text: 'Instant booking, no approval wait', included: true),
        MembershipFeature(text: '30% discount + loyalty credits', included: true),
        MembershipFeature(text: 'Dedicated concierge line — 24/7', included: true),
        MembershipFeature(text: 'Priority fleet selection + first access', included: true),
        MembershipFeature(text: 'Anywhere-in-UAE delivery, any hour', included: true),
        MembershipFeature(text: 'VIP member events & track days', included: true),
        MembershipFeature(text: 'Named personal account manager', included: true),
      ],
      highlighted: false,
      badge: 'Apex Exclusive',
      ctaLabel: 'Apply for Apex',
    ),
  ];
}
