"""Add Memberships

Revision ID: 08af6a0eff18
Revises: f1d840502fd7
Create Date: 2026-07-08 13:21:13.802027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08af6a0eff18'
down_revision: Union[str, Sequence[str], None] = 'f1d840502fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('price_per_month', sa.Float(), nullable=False),
    sa.Column('price_per_year', sa.Float(), nullable=True),
    sa.Column('highlighted', sa.Boolean(), nullable=True),
    sa.Column('badge', sa.String(length=100), nullable=True),
    sa.Column('cta_label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_tiers_id'), 'membership_tiers', ['id'], unique=False)
    op.create_table('membership_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['membership_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_features_id'), 'membership_features', ['id'], unique=False)
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'created_at')
    op.drop_index(op.f('ix_membership_features_id'), table_name='membership_features')
    op.drop_table('membership_features')
    op.drop_index(op.f('ix_membership_tiers_id'), table_name='membership_tiers')
    op.drop_table('membership_tiers')
    # ### end Alembic commands ###
